import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ThemeProvider from "@/context/ThemeContext";
import "./globals.css";
import { IChildren } from "@/types/index.types";
import { UserProvider } from "@/context/UserContext";
import { UIDataProvider } from "@/context/UIDataContext";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: IChildren) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Toaster position="top-right" richColors />
				<UserProvider>
					<ThemeProvider>
						<UIDataProvider>{children}</UIDataProvider>
					</ThemeProvider>
				</UserProvider>
			</body>
		</html>
	);
}
